### PR TITLE
90 fix(api/fixprops) automatization

### LINKED ISSUE #90: fix(api/fixprops): Automatization
Sacando todos los autodate y automatized

### PR DESCRIPTION
**Pull request by benjapadilla1**
Sacando los autodate y los automatized

### CODE REVIEW

**Review by daviddcordoba — DISMISSED** [review]
amazin

**Review by lucasgrav — DISMISSED** [review]
nice

**Review by lucasgrav — APPROVED** [review]
pls automation

**Review by daviddcordoba — APPROVED** [review]
amasin

**Review by RodrigoSpano — APPROVED** [review]
please dont touch the db.js mate! dont give up!

**Pull request merged**
