### PR TITLE
feat(api/profile): profile get and delete controllers

### LINKED ISSUE #53: feature(api/user): handling user data
- [x] crear controller q devuelva data mediante id del token
- [x] mover controller de deleteUser, desde /auth hasta la nueva ruta = /profile

### PR DESCRIPTION
**Pull request by RodrigoSpano**
movi la ruta delete user al path /profile
cree ruta getUserInfo para el front

### CODE REVIEW

**Review by benjapadilla1 — DISMISSED** [review]
Nice changes

**Review by daviddcordoba — DISMISSED** [review]
well done!

**Review by daviddcordoba — APPROVED** [review]
well done again

**Review by benjapadilla1 — APPROVED** [review]
Nice again

**Pull request merged**
