### PR TITLE
adding swagger example

### LINKED ISSUE #5: fix(api/swagger): Bug in swagger config
Fixing the swagger config

### PR DESCRIPTION
**Pull request by benjapadilla1**

### CODE REVIEW

**Review by RodrigoSpano — APPROVED** [review]
best performance ever!

**Comment by lucasgrav** [comment]
very good, but please specify in the comments what you are going to do in this issue

**Review by daviddcordoba — APPROVED** [review]
sensational

**Review by lucasgrav — APPROVED** [review]
very good my querido, please write better comments

**Pull request merged**
